FROM node:22-bookworm-slim AS deps
WORKDIR /app
COPY package.json ./
RUN npm install

FROM node:22-bookworm-slim AS build
WORKDIR /app
ARG NEXT_PUBLIC_SOLANA_RPC_URL=https://api.mainnet-beta.solana.com
ARG NEXT_PUBLIC_ZAPP_PUBLIC_LAUNCH_ENABLED=false
ARG NEXT_PUBLIC_APP_URL=https://zapp-web-production.up.railway.app
ENV NEXT_PUBLIC_SOLANA_RPC_URL=$NEXT_PUBLIC_SOLANA_RPC_URL
ENV NEXT_PUBLIC_ZAPP_PUBLIC_LAUNCH_ENABLED=$NEXT_PUBLIC_ZAPP_PUBLIC_LAUNCH_ENABLED
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:22-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
RUN apt-get update   && apt-get install -y --no-install-recommends postgresql-client ca-certificates   && rm -rf /var/lib/apt/lists/*
COPY --from=build /app/package.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/.next ./.next
COPY --from=build /app/db ./db
EXPOSE 3000
CMD ["npm","run","start"]
